name: chat_app_ui
description: "A new Flutter project for Easy Chat app with Firebase."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  shared_preferences: ^2.2.3

  firebase_core: ^3.2.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.1.0

  meta: ^1.11.0
  google_sign_in: ^7.2.0
  image_picker: ^1.2.3
  http: ^1.6.0
  video_player: ^2.13.0
  url_launcher: ^6.3.2
  dio: ^5.11.0
  pretty_dio_logger: ^1.4.0
  flutter_stripe: ^13.1.0
  webview_flutter: ^4.14.1
  flutter_local_notifications: ^22.2.0
  firebase_messaging: ^15.2.10
  flutter_dotenv: ^6.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    # خط بوبينز المتاح عندك في الفولدر
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    # الخط العربي المميز المتاح عندك في الفولدر
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
